### ISSUE TITLE
댓글 기능

### ISSUE THREAD

**Issue by hellonayeon** [yum-yum-trend/backend#10]
* 댓글
|__ 게시물 상세 모달에서 `댓글` 추가

by profoundsea25
- [x] CommentController (11/28)
- [x] CommentService (11/28)
- [x] CommentEntity (11/28)
- [x] Comment Request & Response DTO (11/28)
- [x] 동작 확인 (11/28)
- [x] TEST : 댓글 저장 (11/29)
- [x] TEST : 댓글 삭제 (11/29)

**Comment by profoundsea25** [comment]
제가 스리슬쩍 하겠읍니다

**Comment by profoundsea25** [comment]
**11/28 이슈 : SOLID 지향 설계?**

현재 댓글을 불러오는 방법에 있어,
- ArticleService에서 getArticle에 댓글을 추가해 좋아요, 해쉬 태그 등과 함께 불러올지,
- CommentService를 따로 만들어서 댓글을 불러오는 메서드(getArticleComments)를 따로 만들지 

를 고민했습니다.

고민의 이유는 SOLID 중에서 "SRP 단일 책임 원칙" 때문입니다. "한 클래스는 하나의 책임만을 가진다."라는 뜻인데, ArticleService의 getArticle 메서드가 여러 책임들이 계속 추가되는 것이 아닌가하는 생각이 들었습니다.

Comment를 불러오는 메서드를 나누게 되었을 경우, 장점이라면 댓글 부분을 따로 분리했으니 유지/보수에 유리하다는 점이 있겠습니다. 단점이라면 서버 통신 리소스를 더 쓴다는 점(API를 하나 더 추가)이겠네요.

일단은 Comment 부분을 Service, Controller 등을 따로 설계했습니다. 나중에 문제가 되면 책임지고 ArticleService, ArticleController에 통합하도록 하겠습니다.

**Comment by hellonayeon** [comment]
말씀을 들어보니 왜 프론트단의 코드들이 거대해지고 있는지 알 것 같네요..🥺
추후에 `Likes` 관련 계층들도 분리하는게 좋을 것 같다는 생각이 들어요! 고민 나눠주셔서 감사합니다 ~
