### ISSUE TITLE
위치정보 등록 기능 구현

### ISSUE THREAD

**Issue by KKHoon210417** [yum-yum-trend/backend#21]
#### 위치정보 등록 API 구현

- [x] 위치 정보 테이블 생성
  - 가게 이름
  - 도로명 주소 or 기존 주소
  - 카테고리 : 음식점 > 한식 > 순대 > 신의주참쌀순대
    -> 폴더 구조이기 때문에 또 테이블을 만들어야할지도...?
    -> 있으면 Trend 구현할 때 도움이 될듯.

 ---

 - [x] 위치 정보 등록 API 구현
  - 게시글 등록 API에 같이 등록가능하도록 설계

**Comment by hellonayeon** [comment]
해결 했습니다~ 한번 푸시 하셔서 테스트 부탁드립니다 🥺

프론트쪽에서 JSON 형식으로 변경해서 보냈습니다!
**index.js / function addArticle()**
```js
    let formData = new FormData();
    
    ...

    let gLocationInfoJson = JSON.stringify(gLocationInfo);
    formData.append("location", gLocationInfoJson);

    ...
```
