### ISSUE TITLE
배포

### ISSUE THREAD

**Issue by profoundsea25** [yum-yum-trend/backend#64]
- [x] github action - main.yml 스크립트 작성
- [x] 배포용 파일 작성
- [x] 테스트 코드 수정
- [x] 배포 테스트
- [x] 프론트와 엔드포인트 연결
<br></br>
- [ ] #76
- [x] main.yml에서 deploy/application.jar를 인지하지 못하는 현상 수정
- [x] application-*.yml 파일들의 민감 정보 처리 방법 모색

**Comment by hellonayeon** [comment]
테스트 코드를 작성하다 저번에 해준님께서 보여주신 좋아요 관련 테스트코드 오류가 동일하게 났었습니다.
제 로컬 환경의 경우 데이터베이스 관련 설정의 문제였고, `application.yml`에 다음 속성을 추가해서 해결했습니다. 
MySQL로 테스트할때는 같은 오류가 발생하지 않아 수정하지 않았지만 MySQL 관련 설정도 도움이 될까하여 올립니다.

* H2 
  * `spring.jpa.database-platform=database-platform: org.hibernate.dialect.H2Dialect # 나중에 mysql 로 변경`
* MySQL 
  * `spring.jpa.database-platform=database-platform: org.hibernate.dialect.MySQL5Dialect`
